--------------------------------------------------------
--  DDL for Table TC_EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "APEX"."TC_EMPLOYEE" 
   (	"EMP_ID" NUMBER, 
	"EMP_NAME" VARCHAR2(100 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into APEX.TC_EMPLOYEE
SET DEFINE OFF;
Insert into APEX.TC_EMPLOYEE (EMP_ID,EMP_NAME,START_DATE,END_DATE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (100,'employee1',to_date('30-MAR-20 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),null,to_date('30-MAR-20 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,to_date('30-MAR-20 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,1);
Insert into APEX.TC_EMPLOYEE (EMP_ID,EMP_NAME,START_DATE,END_DATE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (101,'employee2',to_date('30-APR-20 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),null,to_date('30-APR-20 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,to_date('30-APR-20 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,1);
Insert into APEX.TC_EMPLOYEE (EMP_ID,EMP_NAME,START_DATE,END_DATE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (102,'employee3',to_date('30-APR-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),null,to_date('30-APR-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,to_date('30-APR-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,1);
