--------------------------------------------------------
--  DDL for Table TC_USER_ROLES
--------------------------------------------------------

  CREATE TABLE "APEX"."TC_USER_ROLES" 
   (	"ROLE_ID" NUMBER, 
	"EMP_ID" NUMBER, 
	"ROLE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into APEX.TC_USER_ROLES
SET DEFINE OFF;
Insert into APEX.TC_USER_ROLES (ROLE_ID,EMP_ID,ROLE) values (10000,100,'Employee');
Insert into APEX.TC_USER_ROLES (ROLE_ID,EMP_ID,ROLE) values (10001,101,'Employee');
Insert into APEX.TC_USER_ROLES (ROLE_ID,EMP_ID,ROLE) values (10002,102,'Admin');
