--------------------------------------------------------
--  DDL for Table TC_USER
--------------------------------------------------------

  CREATE TABLE "APEX"."TC_USER" 
   (	"USER_ID" NUMBER, 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"EMP_ID" NUMBER, 
	"USER_ROLE" VARCHAR2(20 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into APEX.TC_USER
SET DEFINE OFF;
Insert into APEX.TC_USER (USER_ID,USER_NAME,PASSWORD,EMP_ID,USER_ROLE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (100,'employee3@gmail.com','employee31234',102,'ADMIN',to_date('03-SEP-21 10:47:48 AM','DD-MON-RR HH:MI:SS AM'),1,to_date('03-SEP-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,1);
Insert into APEX.TC_USER (USER_ID,USER_NAME,PASSWORD,EMP_ID,USER_ROLE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (101,'employee1@gmail.com','employee11234',100,'EMPLOYEE',to_date('03-SEP-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,to_date('03-SEP-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,1);
Insert into APEX.TC_USER (USER_ID,USER_NAME,PASSWORD,EMP_ID,USER_ROLE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (102,'employee2@gmail.com','employee21234',101,'EMPLOYEE',to_date('03-SEP-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,to_date('03-SEP-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,1);
