--------------------------------------------------------
--  DDL for Table TC_EMPLOYEE
--------------------------------------------------------

  CREATE TABLE TC_EMPLOYEE 
   (EMP_ID           NUMBER, 
    EMP_NUMBER       VARCHAR2(100),   
	FIRST_NAME       VARCHAR2(100),
	LAST_NAME        VARCHAR2(100),
	FULL_NAME        VARCHAR2(100),
	START_DATE       DATE, 
	END_DATE         DATE,
	EMP_DOB          DATE,
	EMAIL            VARCHAR2(50),
	APPROVER         VARCHAR2(100),
	APPROVER_ID      NUMBER,
	APPROVER_NUMBER  VARCHAR2(100),
	CREATION_DATE    DATE, 
	CREATED_BY       NUMBER, 
	LAST_UPDATE_DATE DATE, 
	LAST_UPDATED_BY  NUMBER
   );
   
Insert into APEX.TC_EMPLOYEE (EMP_ID,EMP_NAME,START_DATE,END_DATE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (100,'employee1',to_date('30-MAR-20 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),null,to_date('30-MAR-20 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,to_date('30-MAR-20 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,1);
Insert into APEX.TC_EMPLOYEE (EMP_ID,EMP_NAME,START_DATE,END_DATE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (101,'employee2',to_date('30-APR-20 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),null,to_date('30-APR-20 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,to_date('30-APR-20 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,1);
Insert into APEX.TC_EMPLOYEE (EMP_ID,EMP_NAME,START_DATE,END_DATE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (102,'employee3',to_date('30-APR-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),null,to_date('30-APR-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,to_date('30-APR-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,1);
