CREATE TABLE TC_HOLIDAYS(HOLIDAY_ID       NUMBER,
                         START_DATE       DATE,
						 END_DATE         DATE,
						 HOLIDAY_NAME     VARCHAR2(250),
						 CREATION_DATE    DATE,
						 CREATED_BY       VARCHAR2(150),
						 LAST_UPDATE_DATE DATE,
						 LAST_UPDATED_BY  VARCHAR2(150)
						 );
						 

CREATE SEQUENCE  TC_HOLIDAYS_SEQ  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1 NOORDER NOCYCLE;