--------------------------------------------------------
--  DDL for Table TC_LEAVE
--------------------------------------------------------

  CREATE TABLE "APEX"."TC_LEAVE" 
   (	"LEAVE_ID" NUMBER, 
	"EMP_ID" NUMBER, 
	"LEAVE_TYPE" VARCHAR2(200 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"NO_OF_LEAVES" NUMBER, 
	"DESCRIPTION" VARCHAR2(3000 BYTE), 
	"LEAVE_STATUS" VARCHAR2(30 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into APEX.TC_LEAVE
SET DEFINE OFF;
Insert into APEX.TC_LEAVE (LEAVE_ID,EMP_ID,LEAVE_TYPE,START_DATE,END_DATE,NO_OF_LEAVES,DESCRIPTION,LEAVE_STATUS,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_BY,LAST_UPDATE_LOGIN) values (1,100,'Sick',to_date('23-NOV-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),to_date('25-NOV-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),null,'<p>Sick</p>
','Submitted',to_date('09-AUG-21 12:42:51 PM','DD-MON-RR HH:MI:SS AM'),100,to_date('09-AUG-21 12:44:50 PM','DD-MON-RR HH:MI:SS AM'),null,1);
Insert into APEX.TC_LEAVE (LEAVE_ID,EMP_ID,LEAVE_TYPE,START_DATE,END_DATE,NO_OF_LEAVES,DESCRIPTION,LEAVE_STATUS,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_BY,LAST_UPDATE_LOGIN) values (2,100,'Sick',to_date('04-AUG-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),to_date('05-AUG-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),null,'<p>I am not feeling well.</p>
','Accepted',to_date('05-AUG-21 12:12:47 PM','DD-MON-RR HH:MI:SS AM'),100,to_date('05-AUG-21 02:10:07 PM','DD-MON-RR HH:MI:SS AM'),null,1);
