--------------------------------------------------------
--  DDL for Table TC_PROJECTS
--------------------------------------------------------

  CREATE TABLE "APEX"."TC_PROJECTS" 
   (	"PROJECT_ID" NUMBER, 
	"PROJECT_NAME" VARCHAR2(100 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into APEX.TC_PROJECTS
SET DEFINE OFF;
Insert into APEX.TC_PROJECTS (PROJECT_ID,PROJECT_NAME,START_DATE,END_DATE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (1000,'project1',to_date('05-MAY-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),null,to_date('05-MAY-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,to_date('05-MAY-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,1);
Insert into APEX.TC_PROJECTS (PROJECT_ID,PROJECT_NAME,START_DATE,END_DATE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (1001,'project2',to_date('20-MAR-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),null,to_date('20-MAR-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,to_date('20-MAR-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,1);
Insert into APEX.TC_PROJECTS (PROJECT_ID,PROJECT_NAME,START_DATE,END_DATE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (1002,'project3',to_date('25-JUN-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),null,to_date('25-JUN-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,to_date('25-JUN-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,1);
Insert into APEX.TC_PROJECTS (PROJECT_ID,PROJECT_NAME,START_DATE,END_DATE,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (1003,'project4',to_date('01-JAN-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),null,to_date('01-JAN-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,to_date('01-JAN-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),1,1);
