CREATE TABLE TC_TIMESHEET_NOTES(NOTE_ID         NUMBER,
                                TIMESHEET_ID    NUMBER,
								MONDAY_NOTE     VARCHAR2(4000),
								TUESDAY_NOTE    VARCHAR2(4000),
								WEDNESDAY_NOTE  VARCHAR2(4000),
								THURSDAY_NOTE   VARCHAR2(4000),
								FRIDAY_NOTE     VARCHAR2(4000),
								SATURDAY_NOTE   VARCHAR2(4000),
								SUNDAY_NOTE     VARCHAR2(4000),
								CREATION_DATE   DATE,
								CREATED_BY      VARCHAR2(150),
								LAST_UPDATE_DATE DATE,
								LAST_UPDATED_BY  VARCHAR2(150)
								     );