--------------------------------------------------------
--  DDL for Table TC_TIME_SHEET
--------------------------------------------------------

  CREATE TABLE "APEX"."TC_TIME_SHEET" 
   (	"TIMESHEET_ID" NUMBER, 
	"EMP_ID" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"STATUS" VARCHAR2(10 BYTE), 
	"WEEK_START" DATE, 
	"WEEK_END" DATE, 
	"MONDAY" NUMBER, 
	"TUESDAY" NUMBER, 
	"WEDNESDAY" NUMBER, 
	"THURSDAY" NUMBER, 
	"FRIDAY" NUMBER, 
	"SATURDAY" NUMBER, 
	"SUNDAY" NUMBER, 
	"TOTAL_HOURS" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER,
	"TASK_ID"           NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into APEX.TC_TIME_SHEET
SET DEFINE OFF;
Insert into APEX.TC_TIME_SHEET (TIMESHEET_ID,EMP_ID,PROJECT_ID,STATUS,WEEK_START,WEEK_END,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,TOTAL_HOURS,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (10000,100,1000,'Submitted',to_date('28-JUN-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),to_date('04-JUL-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),10,10,10,10,10,null,null,50,to_date('01-AUG-21 08:39:34 PM','DD-MON-RR HH:MI:SS AM'),1,to_date('01-AUG-21 08:39:34 PM','DD-MON-RR HH:MI:SS AM'),1,1);
Insert into APEX.TC_TIME_SHEET (TIMESHEET_ID,EMP_ID,PROJECT_ID,STATUS,WEEK_START,WEEK_END,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,TOTAL_HOURS,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (10001,100,1000,'Submitted',to_date('26-JUL-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),to_date('01-AUG-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),10,10,10,10,10,null,null,50,to_date('01-AUG-21 09:27:56 PM','DD-MON-RR HH:MI:SS AM'),1,to_date('01-AUG-21 09:27:56 PM','DD-MON-RR HH:MI:SS AM'),1,1);
Insert into APEX.TC_TIME_SHEET (TIMESHEET_ID,EMP_ID,PROJECT_ID,STATUS,WEEK_START,WEEK_END,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY,TOTAL_HOURS,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN) values (10002,100,1000,'Submitted',to_date('02-AUG-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),to_date('08-AUG-21 12:00:00 AM','DD-MON-RR HH:MI:SS AM'),10,10,10,10,10,null,null,50,to_date('01-AUG-21 09:28:40 PM','DD-MON-RR HH:MI:SS AM'),1,to_date('01-AUG-21 09:28:40 PM','DD-MON-RR HH:MI:SS AM'),1,1);
